### ISSUE TITLE
MUL equivalence

### ISSUE THREAD

**Issue by pgarba** [maxtuno/PEQNP#1] opened 2020-07-31 07:44 UTC
Hi,

@fvrmatteo and I are looking into a problem that we can't solve so far with some SAT solver we tried. With PEQNP we also run into the same issue. Do you think this problem is solvable with PEQNP or is there a specific reason why it's failing?

Thanks,
Peter

```
import peqnp as pn

mask = 0xFFFF

def myNot(x):
  return (-x - 1) & mask

def myAnd(x, y):
  return (x & y) & mask

def myOr(x, y):
  return (x | y) & mask

def myMul(x, y):
  return (x * y) & mask

def myAdd(x, y):
  return (x + y) & mask

pn.engine(bits=16)
x = pn.integer()
y = pn.integer()

assert myMul(x, y) != myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x))))

if pn.satisfy():
    print(x, y)
    print("myAnd(x, y): ", myAnd(x, y))
    print("myOr(x, y): ", myOr(x, y))
    print("myMul(x, y): ", myMul(x, y))
    print("myNot(x): ", myNot(x))
    print("myNot(y): ", myNot(y))
    print(myMul(x, y), myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x)))))

**Comment by maxtuno** [comment] 2020-07-31 10:58
Hello,

The problem is that PEQNP works with positive integers, and with integers where x - y >= 0, the "myNot" definition has this problem, I change by an equivalent definition... (check this)

Try this, work for you?

Thanks for comment... 

```python
import peqnp as pn

mask = 0xFFFFFFFFFFFFFFFF

def myNot(x):
  return mask - x

def myAnd(x, y):
  return (x & y) & mask

def myOr(x, y):
  return (x | y) & mask

def myMul(x, y):
  return (x * y) & mask

def myAdd(x, y):
  return (x + y) & mask

pn.engine(bits=mask.bit_length())

x = pn.integer(key='x')
y = pn.integer(key='y')

assert myMul(x, y) != myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x))))

if pn.satisfy(turbo=True, log=True):
    print(x, y)
    print("myAnd(x, y): ", myAnd(x, y))
    print("myOr(x, y): ", myOr(x, y))
    print("myMul(x, y): ", myMul(x, y))
    print("myNot(x): ", myNot(x))
    print("myNot(y): ", myNot(y))
    print(myMul(x, y), myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x)))))
else:
    print('Infeasible ...')
```
```
c                                          
c    ██████  ██▓     ██▓ ███▄ ▄███▓▓█████  
c  ▒██    ▒ ▓██▒    ▓██▒▓██▒▀█▀ ██▒▓█   ▀  
c  ░ ▓██▄   ▒██░    ▒██▒▓██    ▓██░▒███    
c    ▒   ██▒▒██░    ░██░▒██    ▒██ ▒▓█  ▄  
c  ▒██████▒▒░██████▒░██░▒██▒   ░██▒░▒████▒ 
c  ▒ ▒▓▒ ▒ ░░ ▒░▓  ░░▓  ░ ▒░   ░  ░░░ ▒░ ░ 
c  ░ ░▒  ░ ░░ ░ ▒  ░ ▒ ░░  ░      ░ ░ ░  ░ 
c  ░  ░  ░    ░ ░    ▒ ░░      ░      ░    
c        ░      ░  ░ ░         ░      ░  ░ 
c                                          
c           http://www.peqnp.com           
c                                          
c Reduced to 18584 vars, 108842 cls (grow=0)
c Reduced to 18550 vars, 108844 cls (grow=1)
c Reduced to 18549 vars, 108846 cls (grow=2)
c Reduced to 18311 vars, 109322 cls (grow=3)
c Reduced to 18307 vars, 109334 cls (grow=4)
c Reduced to 18305 vars, 109340 cls (grow=5)
c Reduced to 18303 vars, 109344 cls (grow=6)
c No. effective iterative eliminations: 6
c 4.8503% 1251       
3 3355903368356134910
myAnd(x, y):  2
myOr(x, y):  3355903368356134911
myMul(x, y):  10067710105068404730
myNot(x):  -18446744073709551612
myNot(y):  -15090840705353416705
10067710105068404730 6711806736712269834
9.37s user 0.09s system 95% cpu 9.853 total
```

**Comment by fvrmatteo** [comment] 2020-07-31 11:50
Hello,

thank you for pointing out the issue with the positive integers and sorry for the lack of context (more on this later)!

We originally tried with the wrong `not` implementation because using the one you shared was giving us unexpected results.

Specifically what is currently being tested is a tautology, the left hand and right hand expressions are computing the `mul` between the 2 integers. The right hand expression is a mixed-boolean-arithmetic expression like the one described in [this question](https://math.stackexchange.com/questions/1133527/mixed-boolean-arithmetic-identity).

The assertion should test if there's any value for `x` and `y` for which the tautology doesn't hold, and testing your updated example it seems like a counter-example is found, but that is leading to the left hand side and right hand side being identical (which breaks the assumption):

```
x = 1701, y = 13
myAnd(x, y):  5
myOr(x, y):  1709
myMul(x, y):  22113
myNot(x):  63834
myNot(y):  65522
22113 22113 <- this is expected to be different if the assertion is satisfied.
```

The expected result is therefore `Infeasible...` unless we are doing something wrong on our side. Are we misinterpreting the output or the assertion is satisfied by wrong values?

**Comment by maxtuno** [comment] 2020-07-31 11:58
Yes, Thanks I realized after a while, here it is corrected, we must ensure that mask - x >= 0, is ok now?

```python
import peqnp as pn

mask = 0xFFFFFFFFFFFFFFFF


def myNot(x):
    assert mask >= x
    return mask - x


def myAnd(x, y):
    return (x & y) & mask


def myOr(x, y):
    return (x | y) & mask


def myMul(x, y):
    return (x * y) & mask


def myAdd(x, y):
    return (x + y) & mask


pn.engine(bits=mask.bit_length())

x = pn.integer(key='x')
y = pn.integer(key='y')

assert myMul(x, y) != myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x))))

if pn.satisfy(turbo=True, log=True, cnf_path='equivalence.cnf', proof_path='equivalence.proof'):
    x, y = pn.values([x, y])
    print(x, y)
    print("myAnd(x, y): ", myAnd(x, y))
    print("myOr(x, y): ", myOr(x, y))
    print("myMul(x, y): ", myMul(x, y))
    print("myNot(x): ", myNot(x))
    print("myNot(y): ", myNot(y))
    print(myMul(x, y), myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x)))))
else:
    print('Infeasible ...')
```
```
c                                          
c    ██████  ██▓     ██▓ ███▄ ▄███▓▓█████  
c  ▒██    ▒ ▓██▒    ▓██▒▓██▒▀█▀ ██▒▓█   ▀  
c  ░ ▓██▄   ▒██░    ▒██▒▓██    ▓██░▒███    
c    ▒   ██▒▒██░    ░██░▒██    ▒██ ▒▓█  ▄  
c  ▒██████▒▒░██████▒░██░▒██▒   ░██▒░▒████▒ 
c  ▒ ▒▓▒ ▒ ░░ ▒░▓  ░░▓  ░ ▒░   ░  ░░░ ▒░ ░ 
c  ░ ░▒  ░ ░░ ░ ▒  ░ ▒ ░░  ░      ░ ░ ░  ░ 
c  ░  ░  ░    ░ ░    ▒ ░░      ░      ░    
c        ░      ░  ░ ░         ░      ░  ░ 
c                                          
c           http://www.peqnp.com           
c                                          

Infeasible ...
peqnp@iMac code % drat-trim equivalence.cnf equivalence.proof
c turning on binary mode checking
c parsing input formula with 26227 variables and 125411 clauses
c finished parsing, read 2 bytes from proof file
c UNSAT via unit propagation on the input instance
c 313 of 125411 clauses in core                            
c 1 of 2 lemmas in core using 313 resolution steps
c 0 RAT lemmas in core; 0 redundant literals in core lemmas
s VERIFIED
c verification time: 0.351 seconds
```

**Comment by fvrmatteo** [comment] 2020-07-31 12:04
Chaging the assertion to `assert myMul(x, y) == myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x))))` should lead to the expression to be satisfiable and to a pair of `x` and `y` being generated I think, although it is returning `Unfeasible...` in that case too.

**Comment by maxtuno** [comment] 2020-07-31 12:14
Try now, solution is increase the bits, and ensure that values are in "valid" range.


```python
pn.engine(bits=mask.bit_length() + 1)
assert x <= 0 <= mask
```

```python
import peqnp as pn

mask = 0xFFFF


def myNot(x):
    assert x <= 0 <= mask
    return mask - x


def myAnd(x, y):
    return (x & y) & mask


def myOr(x, y):
    return (x | y) & mask


def myMul(x, y):
    return (x * y) & mask


def myAdd(x, y):
    return (x + y) & mask


pn.engine(bits=mask.bit_length() + 1)

x = pn.integer(key='x')
y = pn.integer(key='y')

assert myMul(x, y) != myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x))))

if pn.satisfy(turbo=True, log=True, cnf_path='equivalence.cnf', proof_path='equivalence.proof'):
    x, y = pn.values([x, y])
    print(x, y)
    print("myAnd(x, y): ", myAnd(x, y))
    print("myOr(x, y): ", myOr(x, y))
    print("myMul(x, y): ", myMul(x, y))
    print("myNot(x): ", myNot(x))
    print("myNot(y): ", myNot(y))
    print(myMul(x, y), myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x)))))
else:
    print('Infeasible ...')
```

```
EQUIVALENCE
0 0
myAnd(x, y):  0
myOr(x, y):  0
myMul(x, y):  0
myNot(x):  65535
myNot(y):  65535
0 0
```

```
NEGATION
c turning on binary mode checking
c parsing input formula with 2130 variables and 9118 clauses
c finished parsing, read 2 bytes from proof file
c UNSAT via unit propagation on the input instance
c 1473 of 9118 clauses in core                            
c 1 of 2 lemmas in core using 1473 resolution steps
c 0 RAT lemmas in core; 0 redundant literals in core lemmas
s VERIFIED
c verification time: 0.192 seconds
```

**Comment by fvrmatteo** [comment] 2020-07-31 12:40
@maxtuno I tested the latest solution you proposed involving the bit increasing and assertion related to the range and it seems that it is working just fine in both the equivalence and non-equivalence assertions. I don't know if it is an issue with GitHub or if you noticed an error in the proposed solution, but I can't see your message here on GitHub (only received it via email).

**Comment by maxtuno** [comment] 2020-07-31 13:49
Well, go to the original formulation, only need range the variables and increase the bits bi 1, the model in this case with adequate constraint work well, and yes is very difficult, you can try with the masks 0xF, 0xFF, 0xFFF, 0xFFFF and see this work well, 0xFFFF (is hard). the proof generated with SLIME version mounted on PEQNP is bad generated, but y proof this with SLIME 5 Cloud, and current running drat-trim is a long proof...

Now is razonable that the problem increase in time with the amount of bits, that is equivalent to increase the search space exponentially...

```python
pn.engine(bits=mask.bit_length() + 1)
pn.apply_single([x, y], lambda c: c <= mask)
```

0xF
Infeasible ...
python3 equivalence.py  0.05s user 0.02s system 97% cpu 0.069 total

 0xFF
Infeasible ...
python3 equivalence.py  2.70s user 0.04s system 99% cpu 2.741 total

0xFFF
Infeasible ...
python3 equivalence.py  19.10s user 0.22s system 95% cpu 20.230 total

0xFFFF
Infeasible ...
python3 equivalence.py  330.67s user 3.10s system 98% cpu 5:39.07 total



```python
import peqnp as pn

mask = 0xFFFF


def myNot(x):
    return (-x - 1) & mask


def myAnd(x, y):
    return (x & y) & mask


def myOr(x, y):
    return (x | y) & mask


def myMul(x, y):
    return (x * y) & mask


def myAdd(x, y):
    return (x + y) & mask


pn.engine(bits=mask.bit_length() + 1)

x = pn.integer(key='x')
y = pn.integer(key='y')

pn.apply_single([x, y], lambda c: c <= mask)

assert myMul(x, y) != myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x))))

if pn.satisfy(turbo=True, log=False, cnf_path='equivalence.cnf', proof_path='equivalence.proof'):
    print(mask, x, y)
    print("myAnd(x, y): ", myAnd(x, y))
    print("myOr(x, y): ", myOr(x, y))
    print("myMul(x, y): ", myMul(x, y))
    print("myNot(x): ", myNot(x))
    print("myNot(y): ", myNot(y))
    print(myMul(x, y), myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x)))))
else:
    print('Infeasible ...')

```

**Comment by maxtuno** [comment] 2020-07-31 14:13
The verification of UNSATISFIABILITY proof... take long time... 

(Let me know if it solves your problem...)

```
peqnp@iMac code % drat-trim equivalence.cnf equivalence.proof
c turning on binary mode checking
c parsing input formula with 2224 variables and 9394 clauses
c finished parsing, read 276532173 bytes from proof file
c detected empty clause; start verification via backward checking
c 7392 of 9394 clauses in core                            
c 2177559 of 2919534 lemmas in core using 417405951 resolution steps
c 0 RAT lemmas in core; 4228768 redundant literals in core lemmas
s VERIFIED
c verification time: 1779.897 seconds
```

**Comment by fvrmatteo** [comment] 2020-07-31 14:18
Thanks for the updates!

We obviously ran into the same issue with other SMT/SAT solvers, it takes too long to prove the unsatisfiability for our needs. Especially because we need to work with 64 bits variables.

I think the issue can be closed!

**Comment by maxtuno** [comment] 2020-07-31 14:29
You are confusing things, DRAT-TRIM (https://github.com/marijnheule/drat-trim) is a validator, PEQNP takes only 5 minutes (300 seconds), to solve your problem, it would have to be seen how long it takes in 64 bits, but it seems to be not much.

Note: The validation took longer than the resolution, very interesting, right?

I try to solve for 64 bits, and put the time to take to solve... and next close this... ok?

**Comment by fvrmatteo** [comment] 2020-07-31 14:37
Sadly for our needs we would need to get the proof phase for the 64 bits equivalence to some seconds (to be reasonable for our analysis). I know it's an absurd requirement, but we would need to crunch hundreds of these queries. There are unsound solutions, but that's not really our cup of tea.

> The validation took longer than the resolution, very interesting, right?

Interesting indeed, sadly we are using the SMT/SAT solvers as black-boxes, so we can't fully grasp the awesomeness of this. Even though seeing a SAT or UNSAT result for one of our queries it's always a joy :)

I'm curious to see your results on the 64 bits problem, looking forward to seeing that and thanks again for your time. I'm not in a hurry to close the issue, we can keep it open for reference and experimentation if you feel like this problem can be tackled in a quicker way.

**Comment by maxtuno** [comment] 2020-07-31 15:28
Try this, with this equivalent model for 128 bits take only 37 seconds, to validate only change this line (note break symmetry with x <= y):

Remarks: You can solve the CNF with any solver (possibly the old and excellent MiniSAT work well)

Tell me if it works for you, it would be excellent!

```python
### Equal
assert (myMul(x, y) / myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x))))) ^ 1 == 0
### Distinct
assert (myMul(x, y) / myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x))))) ^ 1 == 1
```

```python
import peqnp as pn

mask = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF


def myNot(x):
    return (-x - 1) & mask


def myAnd(x, y):
    return (x & y) & mask


def myOr(x, y):
    return (x | y) & mask


def myMul(x, y):
    return (x * y) & mask


def myAdd(x, y):
    return (x + y) & mask


pn.engine(bits=mask.bit_length() + 1)

x = pn.integer(key='x')
y = pn.integer(key='y')

pn.apply_single([x, y], lambda c: c <= mask)

assert (myMul(x, y) / myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x))))) ^ 1 == 1
assert x <= y

if pn.satisfy(turbo=True, log=True, cnf_path='equivalence.cnf', proof_path='equivalence.proof'):
    print(x, y)
    print("myAnd(x, y): ", myAnd(x, y))
    print("myOr(x, y): ", myOr(x, y))
    print("myMul(x, y): ", myMul(x, y))
    print("myNot(x): ", myNot(x))
    print("myNot(y): ", myNot(y))
    print(myMul(x, y), myAdd(myMul(myAnd(x, y), myOr(x, y)), myMul(myAnd(x, myNot(y)), myAnd(y, myNot(x)))))
else:
    print('Infeasible ...')

```

```
c                                          
c    ██████  ██▓     ██▓ ███▄ ▄███▓▓█████  
c  ▒██    ▒ ▓██▒    ▓██▒▓██▒▀█▀ ██▒▓█   ▀  
c  ░ ▓██▄   ▒██░    ▒██▒▓██    ▓██░▒███    
c    ▒   ██▒▒██░    ░██░▒██    ▒██ ▒▓█  ▄  
c  ▒██████▒▒░██████▒░██░▒██▒   ░██▒░▒████▒ 
c  ▒ ▒▓▒ ▒ ░░ ▒░▓  ░░▓  ░ ▒░   ░  ░░░ ▒░ ░ 
c  ░ ░▒  ░ ░░ ░ ▒  ░ ▒ ░░  ░      ░ ░ ░  ░ 
c  ░  ░  ░    ░ ░    ▒ ░░      ░      ░    
c        ░      ░  ░ ░         ░      ░  ░ 
c                                          
c           http://www.peqnp.com           
c                                          
c Reduced to 100579 vars, 645171 cls (grow=0)
c Reduced to 100453 vars, 645153 cls (grow=1)
c Reduced to 97686 vars, 648033 cls (grow=2)
c Reduced to 96813 vars, 649772 cls (grow=3)
c Reduced to 96798 vars, 649824 cls (grow=4)
c Reduced to 96566 vars, 650613 cls (grow=5)
c Reduced to 96402 vars, 650827 cls (grow=6)
c Reduced to 96401 vars, 650832 cls (grow=7)
c Reduced to 96395 vars, 650820 cls (grow=8)
c Reduced to 96148 vars, 652607 cls (grow=9)
c No. effective iterative eliminations: 9
c 32.3862% 58611      
Infeasible ...
python3 equivalence.py  37.69s user 0.51s system 96% cpu 39.763 total
```

```
peqnp@iMac code % drat-trim equivalence.cnf equivalence.proof
c turning on binary mode checking
c parsing input formula with 180057 variables and 808700 clauses
c finished parsing, read 162121376 bytes from proof file
c detected empty clause; start verification via backward checking
c 183794 of 808700 clauses in core                            
c 129054 of 2351656 lemmas in core using 28213890 resolution steps
c 0 RAT lemmas in core; 60549 redundant literals in core lemmas
s VERIFIED
c verification time: 47.846 seconds
```

```
c                                          
c    ██████  ██▓     ██▓ ███▄ ▄███▓▓█████  
c  ▒██    ▒ ▓██▒    ▓██▒▓██▒▀█▀ ██▒▓█   ▀  
c  ░ ▓██▄   ▒██░    ▒██▒▓██    ▓██░▒███    
c    ▒   ██▒▒██░    ░██░▒██    ▒██ ▒▓█  ▄  
c  ▒██████▒▒░██████▒░██░▒██▒   ░██▒░▒████▒ 
c  ▒ ▒▓▒ ▒ ░░ ▒░▓  ░░▓  ░ ▒░   ░  ░░░ ▒░ ░ 
c  ░ ░▒  ░ ░░ ░ ▒  ░ ▒ ░░  ░      ░ ░ ░  ░ 
c  ░  ░  ░    ░ ░    ▒ ░░      ░      ░    
c        ░      ░  ░ ░         ░      ░  ░ 
c                                          
c           http://www.peqnp.com           
c                                          
c Reduced to 92058 vars, 522991 cls (grow=0)
c Reduced to 91929 vars, 522967 cls (grow=1)
c Reduced to 90131 vars, 525123 cls (grow=2)
c Reduced to 89250 vars, 526891 cls (grow=3)
c Reduced to 87401 vars, 534220 cls (grow=4)
c Reduced to 87343 vars, 534429 cls (grow=5)
c Reduced to 87125 vars, 535020 cls (grow=6)
c Reduced to 86452 vars, 539695 cls (grow=7)
c No. effective iterative eliminations: 7
c 32.7576% 59283      
2 226851449749386619090497384623625994241
myAnd(x, y):  0
myOr(x, y):  226851449749386619090497384623625994243
myMul(x, y):  113420532577834774717620161815483777026
myNot(x):  340282366920938463463374607431768211453
myNot(y):  113430917171551844372877222808142217214
113420532577834774717620161815483777026 113420532577834774717620161815483777026
python3 equivalence.py  4.99s user 0.20s system 67% cpu 7.717 total
```

**Comment by fvrmatteo** [comment] 2020-07-31 16:02
I did a quick test now, but I'll do deeper tests during the weekend and report back the results if you don't mind (we have a set of tautologies that we use for test). It seems like it is giving the results we expect, both Equal and Distinct are returning consistent values even without using `assert x <= y`!

So if I understand this correctly, the line `pn.apply_single([x, y], lambda c: c <= mask)` is just applying a constraint on the input variables, forcing them to be in the range `[0, mask]` (which is fine). Then the equal/distinct query is running on the entire 128 bits space. Hence the `assert x <= y` is not really needed, right?

While it seems that the trick is moving the equal/distinct to be executed as `(expected_expression/equivalent_expression) ^ 1 == 1`. I'm not sure I understand the core idea behind this "magic", but would you mind explaining why in this format the query becomes feasible?

Which also directly connects to my other question: would it be possible to replicate this kind of result with Z3? (Not meant to create competition, but genuine question because a lot of analysis tools can easily communicate with Z3 via the SMT2 format, but if PEQNP is the only solver capable of this kind of reason it may be worth creating an interface).

```
from z3 import *

x = BitVec('x', 16)
y = BitVec('y', 16)

exp = ((x&y)*(x|y)+(x&(~y))*((~x)&y))
sol = (x*y)

encoding = (((sol/exp) ^ 1) == 1)

s = Solver()
s.add(encoding)

if s.check() == sat:
    print('FAILURE')
else:
    print('SUCCESS')
```

Again thank you for your time and knowledge sharing.

**Comment by maxtuno** [comment] 2020-07-31 16:18
This is only for speed, is not strictly necessary but do the process more quick... 
``` 
assert x <= y
```

The expression:
```
pn.apply_single([x, y], lambda c: c <= mask) 
```
Its equivalente to:
```
assert x <= mask
assert y <= mask
```

The magic: 
```
(expected_expression/equivalent_expression) ^ 1 == 1
(x / y) == 1 iff x == y
1^z == 0 iff 1 == z
then 
1^z == 1 iff 1 != z iff x != y
```
Remarks: ^ (XOR)

The truth, apart from the name I do not know z3, it would be a job from my unwarranted point of view, but if z3 supports the model (converted to what z3 understands) I change it for a like (<3) ( :) )

That, for me these things are routine, but if it helps you for something, very well, use it!

(send me an email, (see CNF generated) or write to https://twitter.com/maxtuno)

I like to solving problems... :)

**Closed by maxtuno** 2020-07-31 16:18 UTC

**Comment by fvrmatteo** [comment] 2020-07-31 16:27
Yes the mathematical steps were clear, although I didn't expect this to be the change needed to turn a problem requiring hours to solve into something solvable in seconds at such an high bit-width. I somehow expected it to have the same difficulty of just doing `expected_expression == equivalent_expression`. I learned a lot from this exchange, thanks!

```
(expected_expression/equivalent_expression) ^ 1 == 1
(x / y) == 1 iff x == y
1^z == 0 iff 1 == z
then 
1^z == 1 iff 1 != z iff x != y
```

If Z3 won't support this model, it'll be a chance for PEQNP to get an interface for some other tools :) 

If all our tests will pass we'll gladly share the CNF files via email or send a screenshot on Twitter 👍
